version: '3'

services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    depends_on:
      - db
    tty: true
    volumes:
      - ./src:/app
    networks:
      - app-network
    command: "npm start"

  db:
    image: mysql:5.7
    restart: always
    command: --innodb-use-native-aio=0
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app
  
networks:
  app-network:
    driver: bridge

  