version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - ./src:/app
    networks:
      - app-network
    command: npm start
  db:
    image: mysql:5.7
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    healthcheck: 
      test: ["CMD-SHELL", "mysqladmin -h 'localhost' -u root -proot ping --silent"]
      interval: 10s
      timeout: 3s
      retries: 5
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app
  
networks:
  app-network:
    driver: bridge

  