version: '3'

services:
  app:
    build: .
    depends_on:
      - db
    tty: true
    volumes:
      - ./src:/usr/src/app
    command: sh -c "dockerize -wait tcp://db:3306 -timeout 20s && npm start"
    networks:
      - app-network

  db:
    image: mysql:5.7
    restart: always
    command: --innodb-use-native-aio=0
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app
  
networks:
  app-network:
    driver: bridge

  