version: '3'

services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    tty: true
    networks:
      - app-network
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app
  
networks:
  app-network:

  